# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persona.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpersona.proto\x12\x07persona\"-\n\x0eSaludarRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0b\n\x03\x64ia\x18\x02 \x01(\t\"!\n\x0fSaludarResponse\x12\x0e\n\x06saludo\x18\x01 \x01(\t\"\x1d\n\x0c\x41nimoRequest\x12\r\n\x05\x61nimo\x18\x01 \x01(\t\"6\n\rAnimoResponse\x12\r\n\x05\x61nimo\x18\x01 \x01(\t\x12\x16\n\x0e\x65stadoServidor\x18\x02 \x01(\t2\x90\x01\n\x07Persona\x12>\n\x07saludar\x12\x17.persona.SaludarRequest\x1a\x18.persona.SaludarResponse\"\x00\x12\x45\n\x12\x64\x65\x63irEstadoDeAnimo\x12\x15.persona.AnimoRequest\x1a\x16.persona.AnimoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'persona_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALUDARREQUEST']._serialized_start=26
  _globals['_SALUDARREQUEST']._serialized_end=71
  _globals['_SALUDARRESPONSE']._serialized_start=73
  _globals['_SALUDARRESPONSE']._serialized_end=106
  _globals['_ANIMOREQUEST']._serialized_start=108
  _globals['_ANIMOREQUEST']._serialized_end=137
  _globals['_ANIMORESPONSE']._serialized_start=139
  _globals['_ANIMORESPONSE']._serialized_end=193
  _globals['_PERSONA']._serialized_start=196
  _globals['_PERSONA']._serialized_end=340
# @@protoc_insertion_point(module_scope)
