# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import imagen_pb2 as imagen__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in imagen_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ImagenStub(object):
    """Creo el servicio y los métodos que va a tener
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subirImagen = channel.unary_unary(
                '/imagen.Imagen/subirImagen',
                request_serializer=imagen__pb2.mensajeImagen.SerializeToString,
                response_deserializer=imagen__pb2.subirImagenResponse.FromString,
                _registered_method=True)
        self.bajarImagen = channel.unary_unary(
                '/imagen.Imagen/bajarImagen',
                request_serializer=imagen__pb2.mensajeVacio.SerializeToString,
                response_deserializer=imagen__pb2.mensajeImagen.FromString,
                _registered_method=True)


class ImagenServicer(object):
    """Creo el servicio y los métodos que va a tener
    """

    def subirImagen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bajarImagen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagenServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subirImagen': grpc.unary_unary_rpc_method_handler(
                    servicer.subirImagen,
                    request_deserializer=imagen__pb2.mensajeImagen.FromString,
                    response_serializer=imagen__pb2.subirImagenResponse.SerializeToString,
            ),
            'bajarImagen': grpc.unary_unary_rpc_method_handler(
                    servicer.bajarImagen,
                    request_deserializer=imagen__pb2.mensajeVacio.FromString,
                    response_serializer=imagen__pb2.mensajeImagen.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imagen.Imagen', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imagen.Imagen', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Imagen(object):
    """Creo el servicio y los métodos que va a tener
    """

    @staticmethod
    def subirImagen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagen.Imagen/subirImagen',
            imagen__pb2.mensajeImagen.SerializeToString,
            imagen__pb2.subirImagenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def bajarImagen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagen.Imagen/bajarImagen',
            imagen__pb2.mensajeVacio.SerializeToString,
            imagen__pb2.mensajeImagen.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
