# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagen.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cimagen.proto\x12\x06imagen\"\x1f\n\rmensajeImagen\x12\x0e\n\x06imagen\x18\x01 \x01(\x0c\"&\n\x13subirImagenResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"\x0e\n\x0cmensajeVacio2\x8b\x01\n\x06Imagen\x12\x43\n\x0bsubirImagen\x12\x15.imagen.mensajeImagen\x1a\x1b.imagen.subirImagenResponse\"\x00\x12<\n\x0b\x62\x61jarImagen\x12\x14.imagen.mensajeVacio\x1a\x15.imagen.mensajeImagen\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imagen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAJEIMAGEN']._serialized_start=24
  _globals['_MENSAJEIMAGEN']._serialized_end=55
  _globals['_SUBIRIMAGENRESPONSE']._serialized_start=57
  _globals['_SUBIRIMAGENRESPONSE']._serialized_end=95
  _globals['_MENSAJEVACIO']._serialized_start=97
  _globals['_MENSAJEVACIO']._serialized_end=111
  _globals['_IMAGEN']._serialized_start=114
  _globals['_IMAGEN']._serialized_end=253
# @@protoc_insertion_point(module_scope)
