# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import imagenBlob_pb2 as imagenBlob__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in imagenBlob_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StockearteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.altaProducto = channel.unary_unary(
                '/stockearte.Stockearte/altaProducto',
                request_serializer=imagenBlob__pb2.altaProductoRequest.SerializeToString,
                response_deserializer=imagenBlob__pb2.mensajeSimple.FromString,
                _registered_method=True)
        self.mostrarProducto = channel.unary_unary(
                '/stockearte.Stockearte/mostrarProducto',
                request_serializer=imagenBlob__pb2.consultarProductoRequest.SerializeToString,
                response_deserializer=imagenBlob__pb2.mensajeSimple.FromString,
                _registered_method=True)


class StockearteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def altaProducto(self, request, context):
        """PUNTO 1.C
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mostrarProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockearteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'altaProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.altaProducto,
                    request_deserializer=imagenBlob__pb2.altaProductoRequest.FromString,
                    response_serializer=imagenBlob__pb2.mensajeSimple.SerializeToString,
            ),
            'mostrarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.mostrarProducto,
                    request_deserializer=imagenBlob__pb2.consultarProductoRequest.FromString,
                    response_serializer=imagenBlob__pb2.mensajeSimple.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stockearte.Stockearte', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stockearte.Stockearte', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Stockearte(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def altaProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stockearte.Stockearte/altaProducto',
            imagenBlob__pb2.altaProductoRequest.SerializeToString,
            imagenBlob__pb2.mensajeSimple.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def mostrarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stockearte.Stockearte/mostrarProducto',
            imagenBlob__pb2.consultarProductoRequest.SerializeToString,
            imagenBlob__pb2.mensajeSimple.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
