# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imagenBlob.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'imagenBlob.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10imagenBlob.proto\x12\nstockearte\"x\n\x13\x61ltaProductoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x16\n\x0e\x63odigoProducto\x18\x02 \x01(\t\x12\r\n\x05talle\x18\x03 \x01(\t\x12\x0c\n\x04\x66oto\x18\x04 \x01(\t\x12\r\n\x05\x63olor\x18\x05 \x01(\t\x12\r\n\x05stock\x18\x06 \x01(\x05\"2\n\x18\x63onsultarProductoRequest\x12\x16\n\x0e\x63odigoProducto\x18\x01 \x01(\t\" \n\rmensajeSimple\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2\xb0\x01\n\nStockearte\x12L\n\x0c\x61ltaProducto\x12\x1f.stockearte.altaProductoRequest\x1a\x19.stockearte.mensajeSimple\"\x00\x12T\n\x0fmostrarProducto\x12$.stockearte.consultarProductoRequest\x1a\x19.stockearte.mensajeSimple\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imagenBlob_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALTAPRODUCTOREQUEST']._serialized_start=32
  _globals['_ALTAPRODUCTOREQUEST']._serialized_end=152
  _globals['_CONSULTARPRODUCTOREQUEST']._serialized_start=154
  _globals['_CONSULTARPRODUCTOREQUEST']._serialized_end=204
  _globals['_MENSAJESIMPLE']._serialized_start=206
  _globals['_MENSAJESIMPLE']._serialized_end=238
  _globals['_STOCKEARTE']._serialized_start=241
  _globals['_STOCKEARTE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
